openapi: '3.1.0'

info:
  title: Learn express and swagger
  description: A project segment about writing docs
  version: 1.0.0
  contact:
    email: mohammadhammadansari91@gmail.com
    url: 'https://sensational-tartufo-6e38d0.netlify.app/'

# servers:
#   - url: '{protocol}://localhost:{port}/api/{version}'
#     description: for local host secure and regular
#     variables:
#       version:
#         enum: -v1
#           -v2
#       port:
#         enum:
#           - '4000'
#       protocol:
#         enum:
#           - https
#           - http

servers:
  - url: '{protocol}://localhost:{port}/api/{version}'
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      port:
        enum:
          - '4000'
        default: '4000'
      protocol:
        enum:
          - https
          - http
        default: http
